project:
  type: website

website:
  title: "*obseRVe*"
  navbar:
    left:
      - href: atividades/atividades.qmd
        text: Atividades 
      - href: sobre/sobre.qmd
        text: Sobre
    tools:
      - icon: instagram
        href: https://instagram.com  
  page-footer:
    "*obseRVe* - CCA/UFSCar<br>
    {{< var observe-endereco >}}"


format:
  html:
    page-layout: full
    theme:
      light: [flatly, light_mode.scss]
      dark: [darkly, dark_mode.scss]
    css: styles.css
    toc: true



